<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Ejercicio1_Constantes</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ejercicio 1- Campos, propiedades, metodos y constructor\Ejercicio 1- Campos, propiedades, metodos y constructor.csproj" />
  </ItemGroup>

</Project>
